spring:
  application:
    name: co-nect

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url:
    username:
    password:

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDBDialect

  logging:
    level:
      org:
        hibernate:
          SQL: debug
          type:
            descriptor:
              sql: trace

  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:favorable-order-443405-t7-cc0abaa100fb.json
        project-id: favorable-order-443405-t7
        bucket: co-nect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: dGhpc2lzYXZlcnlzZWN1cmVzZWNyZXRrZXl0aGlzaXNhdmVyeXNlY3VyZXNlY3JldGtleQ== # Base64로 인코딩된 키
  access-token-expiration-time: 3600000
  refresh-token-expiration-time: 86400000

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs
